name: NodeJS with Grunt

on:
  push:
    branches: [ Ghost ]
  pull_request:
    branches: [ Ghost ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install ghost-cli@latest -g
        npm install grunt-cli --save-dev
        cd Ghost/current
        npm install
        grunt
