name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: npm ci, build and test
        run: |
          sudo chown -R $USER:$USER *
          sudo npm ci
          npm run build --if-present
          npm test
